spring:
  datasource:
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:15432/library"
    username: dbuser
    password:
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL95Dialect"
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
#         https://vkuzel.com/spring-boot-jpa-hibernate-atomikos-postgresql-exception
          use_jdbc_metadata_defaults: false